[profile.default]
src = "src"
test = "test"
libs = ["lib", "node_modules"]

# Ensure remappings for node_modules
remappings = [
    "@openzeppelin/=/Users/prajitsengupta/Desktop/Blockchain/Blockchain-HR-Management-SmartContract/HumanResources/node_modules/@openzeppelin/",
    "@chainlink/=/Users/prajitsengupta/Desktop/Blockchain/Blockchain-HR-Management-SmartContract/HumanResources/node_modules/@chainlink/",
    "@uniswap/=/Users/prajitsengupta/Desktop/Blockchain/Blockchain-HR-Management-SmartContract/HumanResources/node_modules/@uniswap/"
]
